version: '3.4'

services:
  mysql:
    image: mysql:latest
    container_name: adm_videos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: adm_videos
      MYSQL_ROOT_HOST: '%'
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql:rw